// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD25J6sCNYR2BxqtA8VMdwrOkhrhhDdxFI',
    appId: '1:681520755482:web:b7c09882a48225193c72a3',
    messagingSenderId: '681520755482',
    projectId: 'foody-app-b138a',
    authDomain: 'foody-app-b138a.firebaseapp.com',
    storageBucket: 'foody-app-b138a.appspot.com',
    measurementId: 'G-8G4SD3Q12R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJ9q3JtqK-wECWLJxj8xAhXh0Nx5Wf9s',
    appId: '1:681520755482:android:4e66812f62435e6c3c72a3',
    messagingSenderId: '681520755482',
    projectId: 'foody-app-b138a',
    storageBucket: 'foody-app-b138a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8O2PcHJvdQjasJwOWdnrhCSYZ1zAQSc',
    appId: '1:681520755482:ios:2e2d658427b963c53c72a3',
    messagingSenderId: '681520755482',
    projectId: 'foody-app-b138a',
    storageBucket: 'foody-app-b138a.appspot.com',
    iosClientId: '681520755482-7s3gb9kop452c8v54006or7p18ju8q26.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8O2PcHJvdQjasJwOWdnrhCSYZ1zAQSc',
    appId: '1:681520755482:ios:2e2d658427b963c53c72a3',
    messagingSenderId: '681520755482',
    projectId: 'foody-app-b138a',
    storageBucket: 'foody-app-b138a.appspot.com',
    iosClientId: '681520755482-7s3gb9kop452c8v54006or7p18ju8q26.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD25J6sCNYR2BxqtA8VMdwrOkhrhhDdxFI',
    appId: '1:681520755482:web:36ade2125d5b0e033c72a3',
    messagingSenderId: '681520755482',
    projectId: 'foody-app-b138a',
    authDomain: 'foody-app-b138a.firebaseapp.com',
    storageBucket: 'foody-app-b138a.appspot.com',
    measurementId: 'G-Z0CKWMS0QC',
  );
}
